export enum ReportType {
  API_RESPONSE_TIME = "API_RESPONSE_TIME",
  API_REQUEST_ERR = "API_REQUEST_ERR",
  USER_PLATFORM = "USER_PLATFORM",
  HISTORY_PUSH = "HISTORY_PUSH",
  CUSTOME = "CUSTOME",
}
